# Generated by Django 5.2.6 on 2025-10-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='Enter proficiency % (0-100)')),
                ('color_start', models.CharField(default='#000000', help_text='Gradient start color', max_length=7)),
                ('color_end', models.CharField(default='#ffffff', help_text='Gradient end color', max_length=7)),
            ],
        ),
    ]
