# Generated by Django 5.2.6 on 2025-10-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='color_end',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='color_start',
        ),
    ]
