# Generated by Django 5.2.6 on 2025-10-11 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_skills_color_end_remove_skills_color_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color_end',
            field=models.CharField(blank=True, default='', help_text='Gradient end hex color', max_length=7),
        ),
        migrations.AddField(
            model_name='skills',
            name='color_start',
            field=models.CharField(blank=True, default='', help_text='Gradient start hex color', max_length=7),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Enter proficiency % (0-100)'),
        ),
    ]
